services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-apoc
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data:/data
      - ./plugins:/plugins
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_AUTH=neo4j/llamaindex
    restart: unless-stopped
    networks:
      - internal

  s3:
    image: minio/minio:RELEASE.2023-11-01T18-37-25Z
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=guestuser
      - MINIO_ROOT_PASSWORD=supersecret123
    command: server /data --console-address ":9001"
    volumes:
      - minio_new_volume:/data
    networks:
      - internal
      - public

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # for messaging
      - "15672:15672" # for management UI
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-guest}
    networks:
      - internal
      - public
    restart: unless-stopped

volumes:
  minio_new_volume:

networks:
  internal:
  public:
